# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Hugo Roussaffa a remote geomatic expert
  params:
    description: My portfolio of my geomatics projects
# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr-fr
  contentDir: content/fr
  title: Hugo Roussaffa expert en géomatique à distance 
  params:
    description: Mon portfolio de mes projets géomatiques
  menu:
    main:
      - name: Home
        url: '/'
        weight: 1
      - name: A propos
        url: 'about'
        weight: 2
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
